Fix: window mode in fullscreen
hyprwm/contrib pull request #2
Opened 2022-07-30 03:25 UTC by KyleUltimate

When using window mode in fullscreen, you will still have the selection "window" stuff, when you really shouldn't.
Let me know whether when in fullscreen, should you just copy screen, or select region(area)

2022-08-13 22:45 UTC, fufexan requested changes
Haven't had a chance to test this yet, but these are the the obvious things I'd change by only taking a glance over the code.

2022-08-13 22:45 UTC, fufexan commented on grimblast/grimblast
> +    WINDOWS="$(hyprctl clients -j | jq -r --argjson workspaces "$WORKSPACES" 'map(select([.workspace.id] | inside($workspaces)))' )"
These two calls are redundant (and slow). We should instead set a variable
```sh
CLIENTS=$(hyprctl clients -j)
```
and pass it to `jq` with `<<< $CLIENTS`

2022-08-13 22:45 UTC, fufexan commented on grimblast/grimblast
>    WORKSPACES="$(hyprctl monitors -j | jq -r 'map(.activeWorkspace.id)')"
Same as with clients, this could be `MONITORS=...`.

2022-08-14 03:19 UTC, KyleUltimate commented
Done!
Small question, what the difference between `echo "$WINDOWS" | jq -r '.[] | "\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"' | slurp` this than redirect shell inputing?

2022-08-14 06:04 UTC, fufexan commented
Probably no difference, just the way I did it in my scripts.

2022-08-14 10:27 UTC, merged

2022-09-02 21:00 UTC, fufexan commented
I just noticed, this broke window selection (at least on multiple monitors).

I will be reverting this and potentially implement a check when there's only one monitor present.