add edit option and rofi screenshot applet
hyprwm/contrib pull request #26
Opened 2023-02-25 15:55 UTC by MrDuartePT

Add edit option to grimblast and copy of my rofi screenshot applet script you can see both in action on this video:
https://raw.githubusercontent.com/MrDuartePT/contrib/main/grimblast/preview%20grimblast%20features.mp4

2023-02-25 16:10 UTC, fufexan requested changes
Apart from the changes requested, please also add `grimblast/screenshot.sh` to `.github/workflows/check.yml` and fix any issues found by shellcheck.

2023-02-25 16:10 UTC, fufexan commented on grimblast/grimblast
> +
```suggestion
env_editor_confirm () {
  if [ "printenv | grep $GRIMBLAST_EDITOR" ]; then
    echo "GRIMBLAST_EDITOR is set. Continuing..."
  else
    echo "GRIMBLAST_EDITOR is not set. Defaulting to gimp"
    GRIMBLAST_EDITOR=gimp
  fi
}

```

2023-02-25 16:10 UTC, fufexan commented on grimblast/grimblast
> +  echo "  edit: Open screenshot in image editor of your choice [default is gimp]. (see man page to change it)"
```suggestion
  echo "  edit: Open screenshot in the image editor of your choice (default is gimp). See man page for info."
```

2023-02-25 16:10 UTC, fufexan commented on grimblast/grimblast
> +    MESSAGE="Open Screenshot in Gimp (save in another location after)"
```suggestion
    MESSAGE="Open screenshot in image editor"
```

2023-02-25 16:10 UTC, fufexan commented on grimblast/grimblast.1.scd
> +	on your .bashrc or equivalent) [Exemple:export GRIMPBLAST_EDITOR=gimp]
```suggestion
	Open screenshot in the image editor of your choice. The default is
	gimp, but you can set a different one with the enviroment variable
	$GRIMBLAST_EDITOR. Example: `export GRIMBLAST_EDITOR=gimp`.
```

2023-02-25 16:10 UTC, fufexan commented on grimblast/screenshot.sh
> +gimp='Edit Screenshot'
```suggestion
edit='Edit Screenshot'
```

2023-02-25 16:10 UTC, fufexan commented on grimblast/screenshot.sh
> +		-mesg 'You whant to copy or/and save the screenshot or open in Gimp'
```suggestion
		-mesg 'Copy/save the screenshot or open in image editor'
```

2023-02-25 16:10 UTC, fufexan commented on grimblast/screenshot.sh
> +copy_save_gimp_exit() {
```suggestion
copy_save_editor_exit() {
```

2023-02-25 16:10 UTC, fufexan commented on grimblast/screenshot.sh
> +	echo -e "$copy\n$save\n$copy_save\n$gimp" | copy_save_gimp_cmd
```suggestion
	echo -e "$copy\n$save\n$copy_save\n$edit" | copy_save_edit_cmd
```

2023-02-25 16:10 UTC, fufexan commented on grimblast/screenshot.sh
> +}
```suggestion
copy_save_edit_run () {	
	selected="$(copy_save_edit_exit)"
	if [[ "$selected" == "$copy" ]]; then
		option_chosen=copy
    	${1}
	elif [[ "$selected" == "$save" ]]; then
		option_chosen=save
    	${1}
	elif [[ "$selected" == "$copy_save" ]]; then
		option_chosen=copysave
        ${1}
    elif [[ "$selected" == "$edit" ]]; then
        option_chosen=edit
        ${1}
    fi	
}
```

2023-02-25 16:10 UTC, fufexan commented on grimblast/screenshot.sh
> +		copy_save_gimp_run "shot10"
`copy_save_gimp_run` -> `copy_save_edit_run`

2023-02-25 18:01 UTC, MrDuartePT commented
Thanks for the notice
I will run the workflow and update the pull request

2023-02-25 18:18 UTC, MrDuartePT commented
Spellcheck run fine i just have to comment out the env_editor_confirm function because spellcheck fail to run with this code.
But besides that the check runs fine.
![image](https://user-images.githubusercontent.com/68701049/221373198-9c59c872-5b6f-4af0-96a2-72fbd69b6bfd.png)

2023-02-25 18:50 UTC, fufexan commented
> Spellcheck run fine i just have to comment out the env_editor_confirm function because spellcheck fail to the frist time with this code.

You have to change the condition to `if [ $(printenv GRIMBLAST_EDITOR; echo $?) -eq 0 ]; then`

2023-02-25 21:51 UTC, MrDuartePT commented
Now is all check :)
Thanks for your help and sorry for spelling mistake on the script.
I do some improvements to the screenshot script if you want i can do another video showing the changes.

2023-02-26 01:04 UTC, fufexan commented on README.md
> +Copy of applet screenshot script for rofi
```suggestion
Added the `edit` option to Grimblast. read the [man page](grimblast/grimblast.1.scd) for more information.
A rofi script is also included.
```

2023-02-26 01:05 UTC, fufexan commented
Thanks for fixing the above issues. Can you squash the commits into one (everything) or maybe two (grimblast part in one commit, rofi script in another)?

2023-02-26 02:02 UTC, MrDuartePT commented
Done

2023-02-26 02:08 UTC, MrDuartePT commented
Done add your README.md suggestion and squash everything in one commit.

2023-02-26 02:12 UTC, fufexan approved these changes
LGTM

2023-02-26 02:14 UTC, merged