grimblast: implement --wait
hyprwm/contrib pull request #59
Opened 2023-10-02 18:25 UTC by fufexan

Fixes #57.

Inspired by https://github.com/OctopusET/sway-contrib/commit/695c70deab5279b61df8ec9420030c133599253a.

2023-10-02 18:25 UTC, fufexan commented
@andresilva can you test this and verify it works as intended?

2023-10-02 21:28 UTC, andresilva requested changes
Haven't tested yet.

2023-10-02 21:28 UTC, andresilva commented on grimblast/grimblast
> +WAIT=
Shouldn't this be initialized to "no"?

2023-10-03 11:30 UTC, fufexan commented on grimblast/grimblast
> +WAIT=
Yes, you're right.

2023-10-03 12:48 UTC, andresilva approved these changes
Works as expected.

2023-10-03 13:25 UTC, merged